on: 
  release:
    types: [created, edited]
name: Build Release Binaries
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.14
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: './cmd/fock-cli'
        binary_name: 'fock'
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.14
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        goarch: "amd64"
        goos: linux
        project_path: './cmd/fock-cli'
        binary_name: 'fock'
  release-linux-arm:
    name: release-linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.14
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        goarch: "arm"
        goos: linux
        project_path: './cmd/fock-cli'
        binary_name: 'fock'
  release-linux-arm64:
    name: release-linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.14
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        goarch: "arm64"
        goos: linux
        project_path: './cmd/fock-cli'
        binary_name: 'fock'
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.14
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        goarch: "amd64"
        goos: darwin
        project_path: './cmd/fock-cli'
        binary_name: 'fock'

